#ifndef CLASSFILE_ATTRIBUTES_LOCALVARIABLETYPETABLE_H_
#define CLASSFILE_ATTRIBUTES_LOCALVARIABLETYPETABLE_H_

#include "../Attributes.h"

#endif /* CLASSFILE_ATTRIBUTES_LOCALVARIABLETYPETABLE_H_ */
