#ifndef CLASSFILE_ATTRIBUTES_RUNTIMEVISIBLEPARAMETERANNOTATIONS_H_
#define CLASSFILE_ATTRIBUTES_RUNTIMEVISIBLEPARAMETERANNOTATIONS_H_

#include "Attributes.h"

#endif /* CLASSFILE_ATTRIBUTES_RUNTIMEVISIBLEPARAMETERANNOTATIONS_H_ */
