#ifndef CLASSFILE_ATTRIBUTES_RUNTIMEVISIBLEANNOTATIONS_H_
#define CLASSFILE_ATTRIBUTES_RUNTIMEVISIBLEANNOTATIONS_H_

#include "../Attributes.h"

#endif /* CLASSFILE_ATTRIBUTES_RUNTIMEVISIBLEANNOTATIONS_H_ */
