#ifndef CLASSFILE_ATTRIBUTES_RUNTIMEINVISIBLEANNOTATIONS_H_
#define CLASSFILE_ATTRIBUTES_RUNTIMEINVISIBLEANNOTATIONS_H_

#include "../Attributes.h"

#endif /* CLASSFILE_ATTRIBUTES_RUNTIMEINVISIBLEANNOTATIONS_H_ */
