#ifndef CLASSFILE_ATTRIBUTES_RUNTIMEVISIBLETYPEANNOTATIONS_H_
#define CLASSFILE_ATTRIBUTES_RUNTIMEVISIBLETYPEANNOTATIONS_H_

#include "../Attributes.h"

#endif /* CLASSFILE_ATTRIBUTES_RUNTIMEVISIBLETYPEANNOTATIONS_H_ */
