#ifndef CLASSFILE_ATTRIBUTES_RUNTIMEINVISIBLEPARAMETERANNOTATIONS_H_
#define CLASSFILE_ATTRIBUTES_RUNTIMEINVISIBLEPARAMETERANNOTATIONS_H_

#include "Attributes.h"

#endif /* CLASSFILE_ATTRIBUTES_RUNTIMEINVISIBLEPARAMETERANNOTATIONS_H_ */
