#ifndef CLASSFILE_ATTRIBUTES_RUNTIMEINVISIBLETYPEANNOTATIONS_H_
#define CLASSFILE_ATTRIBUTES_RUNTIMEINVISIBLETYPEANNOTATIONS_H_

#include "../Attributes.h"

#endif /* CLASSFILE_ATTRIBUTES_RUNTIMEINVISIBLETYPEANNOTATIONS_H_ */
